name: Rick Begneaud
favicon: null
layout_spectrum: 0.24787
typography_spectrum: 0.19756
title: Rick Begneaud
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#666666'
    - '#cccccc'
    - '#999999'
    - '#4b4b4b'
  brandStrength: 0.41782286018133163
  lightness: 0.2420542137697339
  saturation: 0.27953060530126095
  rhythmicContrast: 1
purpose: []
